services:
  mysql-8:
    image: mysql:8.0.25
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'mypass'
      # USER: nodejscomplete
      # PWD: mypass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

volumes:
  mysql_data:
