services:
  mysql-8:
    image: mysql:8.0.25
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'mypass'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
  mongo:
    image: mongo:8.0.9
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
